-- begin_generated_IBM_copyright_prolog

-- Licensed Materials - Property of IBM
-- 
-- 5724-N72 5655-WBS
-- 
-- Copyright IBM Corp. 2006, 2009 All Rights Reserved.
-- 
-- US Government Users Restricted Rights - Use, duplication or
-- disclosure restricted by GSA ADP Schedule Contract with
-- IBM Corp.

-- end_generated_IBM_copyright_prolog

-- The WSRR installer will replace the DBNAME, DBUSER and DB2TSDIR variables in this file

-- AUTOCONFIGURE:
-- ==============
-- DB2 will automatically configure 25% of physical memory for the database
-- and the USERSPACE1 tablespace will automatically be configured to use
-- automatic storage, with an initial size of 500M
 CREATE DATABASE WSRRDB ALIAS WSRRDB 
        USING CODESET UTF-8 TERRITORY US
        COLLATE USING IDENTITY PAGESIZE 32768
        USER TABLESPACE
          MANAGED BY AUTOMATIC STORAGE
          AUTORESIZE YES
          INITIALSIZE 500 M
          INCREASESIZE 10 PERCENT
          MAXSIZE NONE;

UPDATE DATABASE CONFIGURATION FOR WSRRDB USING APPLHEAPSZ      8192 IMMEDIATE;
-- applheapsz automatic is only valid on newer versions of db2. 
UPDATE DATABASE CONFIGURATION FOR WSRRDB USING APPLHEAPSZ      AUTOMATIC IMMEDIATE;
UPDATE DATABASE CONFIGURATION FOR WSRRDB USING AVG_APPLS       5    IMMEDIATE;
UPDATE DATABASE CONFIGURATION FOR WSRRDB USING DBHEAP          84000 IMMEDIATE;
UPDATE DATABASE CONFIGURATION FOR WSRRDB USING SHEAPTHRES_SHR  AUTOMATIC;
UPDATE DATABASE CONFIGURATION FOR WSRRDB USING SORTHEAP        AUTOMATIC;
UPDATE DATABASE CONFIGURATION FOR WSRRDB USING LOGBUFSZ        2048 IMMEDIATE;
UPDATE DATABASE CONFIGURATION FOR WSRRDB USING LOGFILSIZ       1000;
UPDATE DATABASE CONFIGURATION FOR WSRRDB USING LOGPRIMARY      25;
UPDATE DATABASE CONFIGURATION FOR WSRRDB USING LOGSECOND       200;
UPDATE DATABASE CONFIGURATION FOR WSRRDB USING LOCKLIST        100000;
UPDATE DATABASE CONFIGURATION FOR WSRRDB USING MAXLOCKS        85;
UPDATE DATABASE CONFIGURATION FOR WSRRDB USING STMTHEAP    32768 IMMEDIATE;
-- stmtheap automatic is only valid on newer versions of db2
UPDATE DATABASE CONFIGURATION FOR WSRRDB USING STMTHEAP    AUTOMATIC IMMEDIATE;

CONNECT TO WSRRDB ;
GRANT IMPLICIT_SCHEMA ON DATABASE TO USER DB2INST1 ;
DISCONNECT CURRENT ;
